name: ngo_app_v2
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  fluttertoast: ^8.2.12
  d_chart: ^3.0.0
  flutter_image_slideshow: ^0.1.6
  charts_flutter: ^0.12.0
  country_picker: ^2.0.27
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  screenshot: ^3.0.0
  google_maps_flutter: ^2.12.3
  razorpay_flutter: ^1.4.0
  http: ^1.4.0
  flutter_datetime_picker: ^1.5.1
  flutter_email_sender: ^7.0.0
  url_launcher: ^6.3.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.2.0
  intl: ^0.17.0
  provider: ^6.1.5
  uuid: ^4.5.1
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.4
  splash_master: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

splash_master:
  color: "#EFFAF1"
  image: "assets/images/transparent.png"
  ios_content_mode: "center"
  android_gravity: "center"
  background_image: "assets/images/transparent.png"
  ios_background_content_mode: "scaleToFill"
  android_background_image_gravity: "fill"
  image_dark_android: "assets/images/transparent.png"
  android_dark_gravity_key: "center"
  color_dark_android: "#EFFAF1"
  android_12_and_above:
    color: "#EFFAF1"
    image: "assets/images/transparent.png"

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
