// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEJEOFp_R7wZIB72FyjSI9e0v3nUhV7No',
    appId: '1:684332864076:web:fc934d5c232ef6d2671ae9',
    messagingSenderId: '684332864076',
    projectId: 'the-ngo-application',
    authDomain: 'the-ngo-application.firebaseapp.com',
    databaseURL: 'https://the-ngo-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-ngo-application.appspot.com',
    measurementId: 'G-J9P49YMYS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5LxVMualnZloDsTftPqZ88TCRn9fJlmU',
    appId: '1:684332864076:android:f2a681122176fd82671ae9',
    messagingSenderId: '684332864076',
    projectId: 'the-ngo-application',
    databaseURL: 'https://the-ngo-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-ngo-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz0iWK8qqJQFfU6TTIqHVHhR8e-EMkwNA',
    appId: '1:684332864076:ios:9a8a083266ab1484671ae9',
    messagingSenderId: '684332864076',
    projectId: 'the-ngo-application',
    databaseURL: 'https://the-ngo-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-ngo-application.appspot.com',
    iosBundleId: 'com.example.ngoAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz0iWK8qqJQFfU6TTIqHVHhR8e-EMkwNA',
    appId: '1:684332864076:ios:9a8a083266ab1484671ae9',
    messagingSenderId: '684332864076',
    projectId: 'the-ngo-application',
    databaseURL: 'https://the-ngo-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-ngo-application.appspot.com',
    iosBundleId: 'com.example.ngoAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAax6PsEw3AYpK7F0elrvEqnT3F8Nd_lF4',
    appId: '1:684332864076:web:56ed07bc0bd3ce07671ae9',
    messagingSenderId: '684332864076',
    projectId: 'the-ngo-application',
    authDomain: 'the-ngo-application.firebaseapp.com',
    databaseURL: 'https://the-ngo-application-default-rtdb.firebaseio.com',
    storageBucket: 'the-ngo-application.appspot.com',
    measurementId: 'G-2SP3MPCK55',
  );
}
